name: Pull Request Review

on:
  pull_request:
    types: [opened, synchronize]
    branches: [master]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd backend
          npm install
          cd ../frontend
          npm install

      - name: Run tests
        run: |
          cd backend
          npm test
          cd ../frontend
          npm test

      - name: Code quality check
        run: |
          npx eslint .

      - name: Performance check
        run: |
          cd backend
          npm run benchmark

      - name: Security audit
        run: |
          cd backend
          npm audit
          cd ../frontend
          npm audit
